# Generated by Django 5.2.7 on 2026-03-16 00:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import teddy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('participant_id', models.CharField(max_length=128)),
                ('study_id', models.CharField(max_length=128)),
                ('session_id', models.CharField(max_length=128)),
                ('expiration_timestamp', models.BigIntegerField(blank=True, null=True)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('session_uuid', models.CharField(max_length=128, unique=True)),
                ('is_completed', models.BooleanField(blank=True)),
                ('recording_uuids', teddy.models.JsonField(default=[])),
                ('session_data', teddy.models.JsonField(default={})),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('participant_id', models.CharField(max_length=128)),
                ('recording_upload_time', models.DateTimeField()),
                ('study_id', models.CharField(max_length=128)),
                ('session_uuid', models.CharField(max_length=128, unique=True)),
                ('video_id', models.CharField(max_length=128)),
                ('video_uuid', models.CharField(max_length=128)),
                ('extra_data', models.CharField(blank=True, max_length=128, null=True)),
                ('video_file', models.FileField(upload_to=teddy.models.upload_video)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Admin User',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
