# Generated by Django 5.2.7 on 2026-03-16 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoupload',
            old_name='recording_upload_time',
            new_name='upload_time',
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 16, 1, 26, 47, 218209)),
            preserve_default=False,
        ),
    ]
