# Generated by Django 5.2.7 on 2026-03-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddy', '0002_rename_recording_upload_time_videoupload_upload_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='session_uuid',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='video_uuid',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
