# Generated by Django 5.2.7 on 2026-03-16 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teddy', '0003_alter_videoupload_session_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessiondata',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='sessiondata',
            old_name='startTime',
            new_name='start_time',
        ),
    ]
