# Generated by Django 5.2.7 on 2026-03-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddy', '0004_rename_endtime_sessiondata_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessiondata',
            name='expiration_timestamp',
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessiondata',
            name='participant_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='sessiondata',
            name='session_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='sessiondata',
            name='study_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='participant_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='study_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
