# Generated by Django 3.2.7 on 2021-09-28 16:11

from django.db import migrations, models
import teddy.models


class Migration(migrations.Migration):

    dependencies = [
        ('teddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsession',
            name='story_recording_file',
            field=models.FileField(blank=True, null=True, upload_to=teddy.models.upload_story),
        ),
        migrations.AlterField(
            model_name='appsession',
            name='video_recording_file',
            field=models.FileField(blank=True, null=True, upload_to=teddy.models.upload_video),
        ),
    ]
