# Generated by Django 3.2.7 on 2021-09-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddy', '0002_auto_20210928_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsession',
            name='session_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appsession',
            name='video_id',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appsession',
            name='video_rating',
            field=models.IntegerField(default=0),
        ),
    ]
