# Generated by Django 3.2.7 on 2021-10-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddy', '0003_auto_20210928_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsession',
            name='installation_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='appsession',
            name='project_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='appsession',
            name='session_label',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='teddyadminuser',
            name='project_names',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
