# Generated by Django 3.2.7 on 2021-11-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddy', '0004_auto_20211005_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsession',
            name='session_type',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
