# Generated by Django 3.2.7 on 2022-02-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddy', '0005_appsession_session_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreapprovedLoginInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, db_index=True, max_length=10, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('deleted_by_user', models.BooleanField(blank=True, default=False)),
                ('user_id', models.CharField(max_length=128)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('project_name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
