# Generated by Django 3.2.7 on 2022-03-03 15:36

from django.db import migrations, models
import django.db.models.deletion


def create_test_project(apps, schema_editor):
    Project = apps.get_model('teddy', 'Project')
    Project.objects.create(name='test', description='test', video_set='babies', randomize_videos=False)


class Migration(migrations.Migration):

    dependencies = [
        ('teddy', '0006_preapprovedlogininformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, db_index=True, max_length=10, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('deleted_by_user', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('video_set', models.CharField(choices=[('babies', 'Babies'), ('misc', 'Miscellaneous'), ('all', 'All')], max_length=32)),
                ('randomize_videos', models.BooleanField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='preapprovedlogininformation',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='teddyadminuser',
            name='project_names',
        ),
        migrations.RunPython(create_test_project),
        migrations.AddField(
            model_name='preapprovedlogininformation',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teddy.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teddyadminuser',
            name='projects',
            field=models.ManyToManyField(to='teddy.Project'),
        ),
    ]
