# Generated by Django 3.2.7 on 2022-03-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddy', '0008_alter_project_randomize_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsession',
            name='final_response',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='appsession',
            name='project_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='appsession',
            name='session_type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='appsession',
            name='video_id',
            field=models.CharField(max_length=128),
        ),
    ]
