# Generated by Django 3.2.7 on 2022-04-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddy', '0009_auto_20220309_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, db_index=True, max_length=10, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('deleted_by_user', models.BooleanField(blank=True, default=False)),
                ('user_id', models.CharField(max_length=128)),
                ('session_id', models.CharField(max_length=128)),
                ('session', models.TextField()),
                ('event', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
